# Generated by Django 6.0.3 on 2026-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='feishu_open_id',
            field=models.CharField(blank=True, help_text='与飞书账号绑定，用于飞书登录', max_length=128, null=True, unique=True, verbose_name='飞书 open_id'),
        ),
        migrations.AddField(
            model_name='employee',
            name='feishu_union_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='飞书 union_id'),
        ),
    ]
