# Generated by Django 6.0.3 on 2026-04-08 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='留空表示全体用户；指定则仅该员工可见。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='仅单人通知使用；全体通知的已读见「通知已读记录」。', null=True, verbose_name='已读时间'),
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='已读时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='users.notification', verbose_name='通知')),
            ],
            options={
                'verbose_name': '通知已读记录',
                'verbose_name_plural': '通知已读记录',
                'constraints': [models.UniqueConstraint(fields=('notification', 'employee'), name='unique_notification_employee_read')],
            },
        ),
    ]
