# Generated by Django 6.0.3 on 2026-04-08 07:00

import django.core.validators
from django.db import migrations, models


def seed_leaderboard_config(apps, schema_editor):
    LeaderboardConfig = apps.get_model("users", "LeaderboardConfig")
    if not LeaderboardConfig.objects.filter(pk=1).exists():
        LeaderboardConfig.objects.create(
            pk=1,
            time_range_label="全部时间",
            home_rank_count=10,
            sidebar_rank_count=6,
            exclude_staff=True,
            footnote="（不含系统管理员）",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_broadcast_and_reads'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range_label', models.CharField(default='全部时间', help_text='展示在积分榜旁，如：全部时间、本月、本季度（当前仍按员工累计积分余额排序）。', max_length=50, verbose_name='时间范围标签')),
                ('home_rank_count', models.PositiveSmallIntegerField(default=10, help_text='首页双列平分展示，例如 10 即左 1–5、右 6–10 名。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='首页上榜人数')),
                ('sidebar_rank_count', models.PositiveSmallIntegerField(default=6, help_text='侧栏排行榜展示前若干名，不超过首页上榜人数。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='「我的学习」侧栏人数')),
                ('exclude_staff', models.BooleanField(default=True, help_text='勾选后不计入 is_staff 与超级用户。', verbose_name='排除管理员账号')),
                ('footnote', models.CharField(blank=True, default='（不含系统管理员）', help_text='显示在标签旁；留空则不显示。', max_length=120, verbose_name='说明脚注')),
            ],
            options={
                'verbose_name': '积分榜显示设置',
                'verbose_name_plural': '积分榜显示设置',
            },
        ),
        migrations.RunPython(seed_leaderboard_config, migrations.RunPython.noop),
    ]
