# Generated by Django 6.0.3 on 2026-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_leaderboardconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, help_text='「我的学习」个人卡片展示；建议正方形图片。', null=True, upload_to='profiles/avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.TextField(blank=True, help_text='一句个性签名，显示在个人卡片。', max_length=500, verbose_name='签名档'),
        ),
    ]
