# Generated by Django 6.0.3 on 2026-04-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employee_avatar_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_home', models.ImageField(blank=True, help_text='建议尺寸 1400×360 px（宽×高），PNG/JPG；全宽横图。', null=True, upload_to='site_banners/home/', verbose_name='首页 Banner')),
                ('banner_my_learning', models.ImageField(blank=True, help_text='建议尺寸 1200×300 px；略扁于其他页。', null=True, upload_to='site_banners/my_learning/', verbose_name='我的学习 Banner')),
                ('banner_points_mall', models.ImageField(blank=True, help_text='建议尺寸 1200×360 px。', null=True, upload_to='site_banners/points_mall/', verbose_name='积分商城 Banner')),
                ('banner_activity_plaza', models.ImageField(blank=True, help_text='建议尺寸 1200×360 px。', null=True, upload_to='site_banners/activity_plaza/', verbose_name='活动广场 Banner')),
            ],
            options={
                'verbose_name': '页面 Banner 图',
                'verbose_name_plural': '页面 Banner 图',
            },
        ),
    ]
