# Generated by Django 6.0.3 on 2026-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sync_staff_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_activity_plaza',
            field=models.ImageField(blank=True, help_text='建议 1200×360 px（约 10:3）。与积分商城同版式：左侧约 68% 宽、object-cover，主体居中。', null=True, upload_to='site_banners/activity_plaza/', verbose_name='活动广场 Banner'),
        ),
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_home',
            field=models.ImageField(blank=True, help_text='建议 1280×360 px（宽×高），PNG/JPG。对应前台主内容区全宽（max-w-7xl），比例约 3.56:1。', null=True, upload_to='site_banners/home/', verbose_name='首页 Banner'),
        ),
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_my_learning',
            field=models.ImageField(blank=True, help_text='建议 1200×300 px（约 4:1）。该页为三栏布局，桌面端 Banner 在中栏（约半宽），图为 object-cover，重要内容请居中，避免左右被裁。', null=True, upload_to='site_banners/my_learning/', verbose_name='我的学习 Banner'),
        ),
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_points_mall',
            field=models.ImageField(blank=True, help_text='建议 1200×360 px（约 10:3）。顶栏左侧约占主区域 68% 宽，图为 object-cover，主体请居中。', null=True, upload_to='site_banners/points_mall/', verbose_name='积分商城 Banner'),
        ),
    ]
