# Generated by Django 6.0.3 on 2026-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_sitebannerconfig_banner_activity_plaza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_activity_plaza',
            field=models.ImageField(blank=True, help_text='建议 1200×360 px（约 10:3）。同积分商城：固定画幅铺满，主体居中。', null=True, upload_to='site_banners/activity_plaza/', verbose_name='活动广场 Banner'),
        ),
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_points_mall',
            field=models.ImageField(blank=True, help_text='建议 1200×360 px（约 10:3）。前台左侧为固定 10:3 画幅并铺满（object-cover），主体宜居中；与右侧侧栏等高时不再被强行拉高留白。', null=True, upload_to='site_banners/points_mall/', verbose_name='积分商城 Banner'),
        ),
    ]
