# Generated by Django 6.0.3 on 2026-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_banner_help_points_mall_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_activity_plaza',
            field=models.ImageField(blank=True, help_text='与积分商城相同：比例 10:3，推荐 1200×360 px（或 2400×720 @2x），勿用正方形；主体居中。', null=True, upload_to='site_banners/activity_plaza/', verbose_name='活动广场 Banner'),
        ),
        migrations.AlterField(
            model_name='sitebannerconfig',
            name='banner_points_mall',
            field=models.ImageField(blank=True, help_text='【比例固定为 宽:高 = 10:3，横图】推荐导出尺寸 1200×360 px（或 2400×720 @2x）。勿用正方形（如 1200×1200），否则左右或上下会被大幅裁切。前台左侧通栏为 10:3 + object-cover，重要视觉请放在中间安全区。', null=True, upload_to='site_banners/points_mall/', verbose_name='积分商城 Banner'),
        ),
    ]
