# Generated by Django 6.0.3 on 2026-04-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_employee_admin_shortcuts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编码')),
                ('description', models.TextField(blank=True, verbose_name='项目说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目目录',
                'verbose_name_plural': '项目目录',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('training', '培训'), ('course', '课程'), ('exam', '考试'), ('homework', '作业'), ('activity', '活动')], max_length=20, verbose_name='模块')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='模块标题')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='模块配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
                'ordering': ['project_id', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'module_type'), name='uniq_project_module_type')],
            },
        ),
    ]
