# Generated by Django 6.0.3 on 2026-04-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_project_projectmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodule',
            name='selected_object_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='已选内容ID'),
        ),
    ]
