# Generated by Django 6.0.3 on 2026-04-02 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='视频文件')),
                ('video_url', models.URLField(blank=True, verbose_name='视频链接')),
                ('reward_points', models.PositiveIntegerField(default=0, verbose_name='学习完成后可获积分')),
                ('course_type', models.CharField(choices=[('required', '必修'), ('elective', '选修')], max_length=20, verbose_name='课程类型')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='学习进度百分比')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
            },
        ),
    ]
