# Generated by Django 6.0.3 on 2026-04-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddConstraint(
            model_name='learningrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'course'), name='unique_employee_course_learning'),
        ),
    ]
