# Generated by Django 6.0.3 on 2026-04-03 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='learningrecord',
            options={'ordering': ['-updated_at'], 'verbose_name': '学习记录', 'verbose_name_plural': '学习记录'},
        ),
        migrations.AddField(
            model_name='course',
            name='cover_url',
            field=models.URLField(blank=True, verbose_name='封面图链接'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='课程时长（分钟）'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近学习时间'),
        ),
    ]
