# Generated by Django 6.0.3 on 2026-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_homepage_course_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exclude_from_hot_ranking',
            field=models.BooleanField(default=False, help_text='勾选后：仍可在首页「推荐」「最新」等展示，但不会出现于「最热课程」排序中（适合仅作展示、不需拼浏览量的课程）。', verbose_name='不参与「最热课程」排行'),
        ),
    ]
