# Generated by Django 6.0.3 on 2026-04-08 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_exclude_hot_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(blank=True, help_text='如：高级讲师、认证讲师', max_length=100, verbose_name='职称/标签')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courses/instructors/', verbose_name='头像')),
                ('photo_url', models.URLField(blank=True, help_text='不上传文件时可填外链', verbose_name='头像链接')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_published', models.BooleanField(default=True, verbose_name='在首页展示')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
