# Generated by Django 6.0.3 on 2026-04-08 02:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('kind', models.CharField(choices=[('exam', '考试'), ('practice', '练习')], default='exam', max_length=20, verbose_name='类型')),
                ('starts_at', models.DateTimeField(blank=True, help_text='不填表示发布后即可参与', null=True, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, help_text='不填表示不限制截止时间', null=True, verbose_name='结束时间')),
                ('pass_score', models.PositiveSmallIntegerField(default=60, help_text='用于判定「通过/未通过」；练习也可沿用。', verbose_name='及格分')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='满分')),
                ('entry_url', models.URLField(blank=True, help_text='可选，跳转外部考试或问卷', verbose_name='答题入口链接')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考试/练习',
                'verbose_name_plural': '考试与练习',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='得分')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='可后台手动填写', null=True, verbose_name='交卷时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='courses.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '考试成绩',
                'verbose_name_plural': '考试成绩',
                'ordering': ['-submitted_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'exam'), name='unique_employee_exam_record')],
            },
        ),
    ]
