# Generated by Django 6.0.3 on 2026-04-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_exam_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='进入考试后的作答时长上限；不填表示不限。与开放时间段相互独立，可随时在后台修改。', null=True, verbose_name='答题限时（分钟）'),
        ),
    ]
