# Generated by Django 6.0.3 on 2026-04-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_exam_duration_and_admin_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='article_body',
            field=models.TextField(blank=True, help_text='内容形式为「文章」时作为主要展示内容；支持多段文字与换行。', verbose_name='文章正文'),
        ),
        migrations.AddField(
            model_name='course',
            name='content_kind',
            field=models.CharField(choices=[('video', '视频'), ('article', '文章')], default='video', help_text='视频课上传/填写视频；图文课主要填写下方「文章正文」。', max_length=10, verbose_name='内容形式'),
        ),
    ]
