# Generated by Django 6.0.3 on 2026-04-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_content_kind_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='article_url',
            field=models.URLField(blank=True, help_text='选填。填写后学员点击在新窗口打开该地址，可保留飞书/语雀/官网等原有排版；不必把全文粘贴进正文。可与简介、站内正文搭配使用。', verbose_name='文章原文链接'),
        ),
        migrations.AlterField(
            model_name='course',
            name='article_body',
            field=models.TextField(blank=True, help_text='站内直接展示的纯文本；从外部粘贴可能丢格式，可改用上方「原文链接」。', verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_kind',
            field=models.CharField(choices=[('video', '视频'), ('article', '文章')], default='video', help_text='视频课上传/填写视频；图文课可使用下方「原文链接」或「文章正文」。', max_length=10, verbose_name='内容形式'),
        ),
    ]
