# Generated by Django 6.0.3 on 2026-04-08 06:53

import django.db.models.deletion
from django.db import migrations, models


def seed_course_categories(apps, schema_editor):
    CourseCategory = apps.get_model("courses", "CourseCategory")
    tree = (
        (
            "球学堂分享",
            0,
            (
                ("AI科普课", 0),
                ("业务全景课", 1),
                ("金融专业课", 2),
                ("战略坊公开课", 3),
                ("其他课程", 4),
            ),
        ),
        (
            "新人专区",
            1,
            (
                ("新员工线上课程", 0),
                ("雪球三问", 1),
                ("基金第一课", 2),
                ("潜力股专区", 3),
            ),
        ),
        (
            "企业百科",
            2,
            (
                ("企业文化", 0),
                ("政策宣导", 1),
                ("品牌活动", 2),
            ),
        ),
        (
            "专业提升",
            3,
            (
                ("职场沟通", 0),
                ("办公效率", 1),
                ("领导力发展", 2),
            ),
        ),
    )
    for root_name, root_order, children in tree:
        root, _ = CourseCategory.objects.get_or_create(
            parent=None,
            name=root_name,
            defaults={"sort_order": root_order},
        )
        if root.sort_order != root_order:
            root.sort_order = root_order
            root.save(update_fields=["sort_order"])
        for child_name, child_order in children:
            child, _ = CourseCategory.objects.update_or_create(
                parent=root,
                name=child_name,
                defaults={"sort_order": child_order},
            )
            if child.sort_order != child_order:
                child.sort_order = child_order
                child.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.coursecategory', verbose_name='上级栏目')),
            ],
            options={
                'verbose_name': '课程目录',
                'verbose_name_plural': '课程目录',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='catalog_category',
            field=models.ForeignKey(blank=True, help_text='选至二级子类，用于首页与全部课程左侧分类筛选。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory', verbose_name='课程目录'),
        ),
        migrations.RunPython(seed_course_categories, migrations.RunPython.noop),
    ]
