# Generated by Django 6.0.3 on 2026-04-08 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='选填。未上传下方「头像」且未填外链时，使用该股员工的个人头像。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_entries', to=settings.AUTH_USER_MODEL, verbose_name='关联员工'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, help_text='管理员上传则优先用于首页展示；留空时可回退到关联员工的个人头像。', null=True, upload_to='courses/instructors/', verbose_name='头像'),
        ),
    ]
