# Generated by Django 6.0.3 on 2026-04-09 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_instructor_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reminder_enabled', models.BooleanField(default=True, help_text='开启后，当您仍有未学完课程时，系统每日最多通过站内通知提醒一次（上海自然日）。', verbose_name='每日学习提醒')),
                ('last_daily_reminder_date', models.DateField(blank=True, help_text='防重复；由系统自动维护。', null=True, verbose_name='上次每日提醒业务日')),
                ('points_notification_enabled', models.BooleanField(default=True, help_text='关闭后，获得每日登录、完课积分时不再写入顶栏「通知」，积分仍正常到账。', verbose_name='学习类积分站内通知')),
                ('verbose_completion_message', models.BooleanField(default=True, help_text='关闭后，标记学完时仅显示简短提示，不再展示积分细则与原因说明。', verbose_name='完课详细提示')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preference', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '学习提醒与完课设置',
                'verbose_name_plural': '学习提醒与完课设置',
            },
        ),
    ]
