# Generated by Django 6.0.3 on 2026-04-09 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_learning_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_deadline',
            field=models.DateTimeField(blank=True, help_text='仅当课程类型为「必修」时生效：学员须在此时间前学完；留空表示不设具体期限（前台仍显示为指派必修）。', null=True, verbose_name='必修完成期限'),
        ),
        migrations.AddField(
            model_name='course',
            name='required_reminder_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='仅必修有效：距「完成期限」前若干天起，知识殿堂「学习任务」等处以醒目样式提醒。留空则按 7 天。', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)], verbose_name='提醒窗口（天）'),
        ),
    ]
