# Generated by Django 6.0.3 on 2026-04-13 02:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_mysql_utf8mb4_retry_per_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='focus_grace_seconds',
            field=models.PositiveSmallIntegerField(default=12, help_text='进入页面后若干秒内不计切屏，避免误触。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='宽限秒数'),
        ),
        migrations.AddField(
            model_name='course',
            name='focus_max_blurs',
            field=models.PositiveSmallIntegerField(blank=True, help_text='留空表示不按次数封禁完课；填写后配合「超限动作」对「标记学完」生效。', null=True, verbose_name='切屏上限（次）'),
        ),
        migrations.AddField(
            model_name='course',
            name='focus_min_hidden_ms',
            field=models.PositiveSmallIntegerField(default=800, help_text='页面处于后台至少该时长才计为 1 次切屏，避免瞬间切换误计。', validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(60000)], verbose_name='计次最小时长（毫秒）'),
        ),
        migrations.AddField(
            model_name='course',
            name='focus_monitor_enabled',
            field=models.BooleanField(default=False, help_text='开启后：学员在本课程页切换标签或窗口失焦达到阈值会提示；可按下方规则禁止「标记学完」。', verbose_name='启用切屏/失焦监测'),
        ),
        migrations.AddField(
            model_name='course',
            name='focus_on_course_exceed',
            field=models.CharField(choices=[('warn_only', '仅提示告警'), ('block_complete', '超过次数禁止标记学完')], default='warn_only', help_text='达到「切屏上限」后：仅告警，或禁止点击「标记为已学完」。', max_length=20, verbose_name='课程超限动作'),
        ),
        migrations.AddField(
            model_name='course',
            name='focus_warn_after_blurs',
            field=models.PositiveSmallIntegerField(default=1, help_text='累计切屏达到此次数起开始弹出提示。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='首次告警阈值（次）'),
        ),
        migrations.AddField(
            model_name='course',
            name='focus_warn_every',
            field=models.PositiveSmallIntegerField(default=1, help_text='之后每再切屏多少次提示一次（1 表示每次都提示）。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='告警间隔（次）'),
        ),
        migrations.AddField(
            model_name='exam',
            name='focus_grace_seconds',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='宽限秒数'),
        ),
        migrations.AddField(
            model_name='exam',
            name='focus_max_blurs',
            field=models.PositiveSmallIntegerField(blank=True, help_text='与「超限动作」配合；留空则只告警不自动交卷。', null=True, verbose_name='切屏上限（次）'),
        ),
        migrations.AddField(
            model_name='exam',
            name='focus_min_hidden_ms',
            field=models.PositiveSmallIntegerField(default=800, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(60000)], verbose_name='计次最小时长（毫秒）'),
        ),
        migrations.AddField(
            model_name='exam',
            name='focus_monitor_enabled',
            field=models.BooleanField(default=False, help_text='开启后：学员经「进入考试」中间页打开外链时，本页失焦会计次；达上限可自动写入 0 分交卷。', verbose_name='启用切屏/失焦监测'),
        ),
        migrations.AddField(
            model_name='exam',
            name='focus_on_exam_exceed',
            field=models.CharField(choices=[('warn_only', '仅提示告警'), ('force_submit_zero', '超限自动交卷（0分）')], default='warn_only', max_length=24, verbose_name='考试超限动作'),
        ),
        migrations.AddField(
            model_name='exam',
            name='focus_warn_after_blurs',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='首次告警阈值（次）'),
        ),
        migrations.AddField(
            model_name='exam',
            name='focus_warn_every',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='告警间隔（次）'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='focus_blur_count_reported',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='交卷时累计切屏次数'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='focus_forced_zero',
            field=models.BooleanField(default=False, help_text='由前台监测超限自动写入；管理员可核对后改分。', verbose_name='因切屏规则记 0 分交卷'),
        ),
        migrations.CreateModel(
            name='ExamFocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blur_count', models.PositiveIntegerField(default=0, verbose_name='累计切屏次数')),
                ('force_ended', models.BooleanField(default=False, verbose_name='已触发规则结束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_focus_sessions', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='courses.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '考试切屏会话',
                'verbose_name_plural': '考试切屏会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseFocusAccum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blur_count', models.PositiveIntegerField(default=0, verbose_name='累计切屏次数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_accums', to='courses.course', verbose_name='课程')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_focus_accums', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '课程切屏累计',
                'verbose_name_plural': '课程切屏累计',
                'constraints': [models.UniqueConstraint(fields=('employee', 'course'), name='uniq_course_focus_accum')],
            },
        ),
    ]
