# Generated by Django 6.0.3 on 2026-04-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_learningrecord_video_playthrough_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='该课程的主讲老师；前台课程详情与首页讲师页会使用。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.instructor', verbose_name='讲师'),
        ),
    ]
