# Generated by Django 6.0.3 on 2026-04-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchanged_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('points_spent', models.PositiveIntegerField(verbose_name='消耗积分')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
                'ordering': ['-exchanged_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('points_cost', models.PositiveIntegerField(verbose_name='所需积分')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
