# Generated by Django 6.0.3 on 2026-04-08 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MallOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='订单号')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称快照')),
                ('points_spent', models.PositiveIntegerField(verbose_name='消耗积分')),
                ('status', models.CharField(choices=[('submitted', '待处理'), ('processing', '备货中'), ('shipped', '配送中'), ('pickup_ready', '待现场领取'), ('completed', '已完成'), ('cancelled', '已取消')], default='submitted', max_length=20, verbose_name='订单状态')),
                ('delivery_type', models.CharField(choices=[('mail', '快递邮寄'), ('pickup', '现场领取')], max_length=10, verbose_name='领取方式')),
                ('recipient_name', models.CharField(blank=True, max_length=50, verbose_name='收件人')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address_detail', models.TextField(blank=True, help_text='省 / 市 / 区及详细地址', verbose_name='邮寄地址')),
                ('pickup_location_note', models.CharField(blank=True, help_text='员工可见的领取地点提示，可由后台维护模板', max_length=300, verbose_name='现场领取说明')),
                ('buyer_remark', models.CharField(blank=True, max_length=500, verbose_name='买家备注')),
                ('logistics_company', models.CharField(blank=True, max_length=100, verbose_name='物流公司')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='运单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_orders', to=settings.AUTH_USER_MODEL, verbose_name='下单员工')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mall_orders', to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商城订单',
                'verbose_name_plural': '商城订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
