# Generated by Django 6.0.3 on 2026-04-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_mall_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopMallSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_pickup_instruction', models.TextField(default='总部行政部前台领取 · 工作日 9:00–18:00 · 请携带订单号与工牌', help_text='在结算页「现场领取」向员工展示；提交订单时会写入该笔订单。修改后仅影响新订单。', verbose_name='默认现场领取说明')),
            ],
            options={
                'verbose_name': '商城展示设置',
                'verbose_name_plural': '商城展示设置',
            },
        ),
        migrations.AlterField(
            model_name='mallorder',
            name='pickup_location_note',
            field=models.TextField(blank=True, help_text='下单时写入的完整说明（含后台默认文案或员工自定义）。', verbose_name='现场领取说明'),
        ),
    ]
