# Generated by Django 6.0.3 on 2026-04-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_seed_shop_mall_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmallsettings',
            name='points_earn_rules',
            field=models.TextField(blank=True, help_text='展示在积分商城「积分体系」区块；留空则使用系统内置默认说明，可在下方直接修改后保存。', verbose_name='积分获取规则（前台展示）'),
        ),
    ]
