# Generated by Django 6.0.3 on 2026-04-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_points_earn_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmallsettings',
            options={'verbose_name': '积分商城：规则与说明', 'verbose_name_plural': '积分商城：规则与说明'},
        ),
        migrations.AlterField(
            model_name='shopmallsettings',
            name='points_earn_rules',
            field=models.TextField(blank=True, help_text='前台路径：积分商城页 →「积分规则」区块。留空则使用系统内置默认文案。建议每条规则单独一行；前 3 行会以三张卡片展示。保存后立即生效。', verbose_name='积分获取规则'),
        ),
    ]
