# Generated by Django 6.0.3 on 2026-04-09 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_points_rules_label_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(blank=True, help_text='用于列表与首页卡片；可不填则截取正文前若干字。', max_length=500, verbose_name='摘要')),
                ('description', models.TextField(blank=True, verbose_name='详情说明')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='shop/trainings/', verbose_name='封面图')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='留空表示不单独限制（仍须在活动未结束前由管理员控制发布状态）。', null=True, verbose_name='报名截止时间')),
                ('location', models.CharField(blank=True, help_text='例：总部 3 楼会议室、或「线上」并可在下方填写链接。', max_length=200, verbose_name='地点 / 形式说明')),
                ('online_meeting_url', models.URLField(blank=True, verbose_name='线上会议链接')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='留空表示不限制；统计待审核+已通过占用名额。', null=True, verbose_name='人数上限')),
                ('is_published', models.BooleanField(default=False, help_text='勾选后：对员工可见并出现在活动广场「培训」分类（仍受时间筛选影响）。', verbose_name='在活动广场展示')),
                ('is_home_featured', models.BooleanField(default=False, help_text='勾选后：出现在网站首页「培训推荐」区块（须同时勾选上方展示）。', verbose_name='首页推荐')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='数字越小越靠前。', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '培训活动',
                'verbose_name_plural': '培训活动',
                'ordering': ['sort_order', '-start_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('message', models.CharField(blank=True, help_text='员工选填：部门、备注需求等。', max_length=300, verbose_name='报名留言')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to=settings.AUTH_USER_MODEL, verbose_name='报名人')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='shop.training', verbose_name='培训活动')),
            ],
            options={
                'verbose_name': '培训报名',
                'verbose_name_plural': '培训报名',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('training', 'employee'), name='uniq_training_registration_per_employee')],
            },
        ),
    ]
