# Generated by Django 6.0.3 on 2026-04-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_training_and_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='可填姓名或「某某团队」；前台详情与列表展示。', max_length=100, verbose_name='讲师'),
        ),
        migrations.AddField(
            model_name='training',
            name='registration_external_url',
            field=models.URLField(blank=True, help_text='选填。若填写，前台将展示「外链报名」入口（可与站内报名并存，由您自行约定使用方式）。', verbose_name='外链报名地址'),
        ),
    ]
