# Generated by Django 6.0.3 on 2026-04-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_training_instructor_external_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['sort_order', '-start_at', '-created_at'], 'verbose_name': '培训活动', 'verbose_name_plural': '培训活动'},
        ),
        migrations.AddField(
            model_name='training',
            name='schedule_note',
            field=models.TextField(blank=True, help_text='灵活排期时在此说明：例「每周三 14:00 共四次」「时间另行通知」。可与上方起止时间同时填写（前台会一并展示）。', verbose_name='时间安排说明'),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='选填；仅填开始时间时表示单次活动开始时刻，结束以说明或后台为准。', null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='training',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='留空表示不单独限制；若未填结束时间，报名是否开放主要受本字段与「发布」控制。', null=True, verbose_name='报名截止时间'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='选填。若不填具体时间，请务必填写下方「时间安排说明」（如：多场次、待定）。', null=True, verbose_name='开始时间'),
        ),
    ]
