# Generated by Django 6.0.3 on 2026-04-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_training_flexible_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='promotional_link_label',
            field=models.CharField(blank=True, help_text='选填。不填则前台显示「查看活动资料」。', max_length=40, verbose_name='资料链接按钮文字'),
        ),
        migrations.AddField(
            model_name='training',
            name='promotional_url',
            field=models.URLField(blank=True, help_text='选填。可填飞书文档、活动介绍页、海报网页等；员工在列表与详情页可点击跳转。与下方「外链报名」用途不同。', verbose_name='宣传/资料链接'),
        ),
    ]
