# Generated by Django 6.0.3 on 2026-04-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_training_promotional_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='applications_category',
            field=models.CharField(choices=[('training', '培训'), ('activity', '活动'), ('selection', '评选'), ('lecturer_cert', '讲师级别认证'), ('course_auth', '课程授权认证'), ('external', '外训'), ('independent', '独立报名')], default='training', help_text='决定该条出现在员工「我的报名」哪一个分类下（已加入/未加入均按此筛选）。默认「培训」；选「活动」等时仍可在活动广场展示，由「在活动广场展示」控制。', max_length=32, verbose_name='「我的报名」中的类型'),
        ),
    ]
