# Generated by Django 6.0.3 on 2026-04-09 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_instructor_employee'),
        ('shop', '0013_training_applications_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmallsettings',
            name='points_course_complete_default',
            field=models.PositiveSmallIntegerField(default=5, help_text='当课程设置「学习完成后可获积分」为 0 时，学完该课按此默认分发放；若课程单独填写了积分则优先生效。', verbose_name='默认完课奖励（分）'),
        ),
        migrations.AddField(
            model_name='shopmallsettings',
            name='points_daily_login',
            field=models.PositiveSmallIntegerField(default=2, help_text='员工每个自然日（上海时区）首次前台登录自动发放，受下方「学习类积分每日上限」约束。', verbose_name='每日登录奖励（分）'),
        ),
        migrations.AddField(
            model_name='shopmallsettings',
            name='points_learning_daily_cap',
            field=models.PositiveSmallIntegerField(default=20, help_text='每日登录 + 学完课程 等学习行为合计最多发放至此分数，超出部分当日不再发放（次日清零重新计算）。', verbose_name='学习类积分每日上限（分）'),
        ),
        migrations.AlterField(
            model_name='training',
            name='applications_category',
            field=models.CharField(choices=[('training', '培训'), ('activity', '活动'), ('selection', '评选'), ('lecturer_cert', '讲师级别认证'), ('course_auth', '课程授权认证'), ('external', '外训'), ('independent', '独立报名')], default='training', help_text='必选其一，与员工前台「我的报名」七个筛选标签一致：培训、活动、评选、讲师级别认证、课程授权认证、外训、独立报名。决定本条出现在哪一个标签下（已加入/未加入均按此筛选）。是否出现在活动广场由下方「在活动广场展示」控制。', max_length=32, verbose_name='「我的报名」分类标签'),
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='发放为正数。', verbose_name='变动积分')),
                ('source', models.CharField(choices=[('daily_login', '每日登录'), ('course_complete', '课程学完')], max_length=32, verbose_name='来源')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('local_date', models.DateField(blank=True, help_text='每日登录奖励对应的上海自然日，防重复发放。', null=True, verbose_name='业务日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_ledger_entries', to='courses.course', verbose_name='关联课程')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '学习积分流水',
                'verbose_name_plural': '学习积分流水',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'daily_login')), fields=('employee', 'source', 'local_date'), name='uniq_points_daily_login_per_employee_day'), models.UniqueConstraint(condition=models.Q(('source', 'course_complete')), fields=('employee', 'source', 'course'), name='uniq_points_course_complete_once')],
            },
        ),
    ]
