# Generated by Django 6.0.3 on 2026-04-09 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_points_ledger_and_learning_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MallShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='如：家、公司', max_length=40, verbose_name='标签')),
                ('recipient_name', models.CharField(max_length=50, verbose_name='收件人')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address_detail', models.TextField(verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '积分商城收货地址',
                'verbose_name_plural': '积分商城收货地址',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
