# Generated by Django 6.0.3 on 2026-04-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_mall_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsledger',
            name='amount',
            field=models.IntegerField(help_text='学习类发放为正数；管理员调整可为正（增加）或负（扣减）。', verbose_name='变动积分'),
        ),
        migrations.AlterField(
            model_name='pointsledger',
            name='source',
            field=models.CharField(choices=[('daily_login', '每日登录'), ('course_complete', '课程学完'), ('admin_adjust', '管理员调整')], max_length=32, verbose_name='来源'),
        ),
    ]
