# Generated by Django 6.0.3 on 2026-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_points_ledger_admin_adjust'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='勾选订单完成后自动写入，便于追踪处理进度。', null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='mallorder',
            name='pickup_notice_sent_at',
            field=models.DateTimeField(blank=True, help_text='占位字段：后台点击通知领取后自动写入；后续可接飞书消息/机器人。', null=True, verbose_name='领取通知时间'),
        ),
    ]
